name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t myapp .
  docker-push-main:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t aakashgautam123/myapp:latest .

      - name: Push Docker image
        run: docker push aakashgautam123/myapp:latest

      - name: Deploy to Amanzon ec2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            NETWORK="app_network"
            docker network create -d bridge $NETWORK || true
            docker network connect app-network nginx || true
            BLUE="app_blue"
            GREEN="app_green"

            #Determine which container is currently live
            if [ "$(docker ps -q -f name=$BLUE)" ]; then
              LIVE=$BLUE
              NEW=$GREEN
            else
              LIVE=$GREEN
              NEW=$BLUE
            fi

            #Assign ports for new container
            if [ "$NEW" = "$BLUE" ]; then
              NEW_PORT=3000
            else
              NEW_PORT=3001

            fi
            
            docker run -d \
              --network $NETWORK \
              --name $NEW \
              -p $NEW_PORT:3000 \
              ${{ secrets.DOCKER_USERNAME }}/myapp:latest

            # Wait for health check
            echo "Waiting for $NEW to become healthy..."
            MAX_RETRIES=20
            RETRY_COUNT=0
            until curl -s -f http://localhost:$NEW_PORT/health || [ $RETRY_COUNT -eq $MAX_RETRIES ]; do
              echo "Waiting for $NEW ($RETRY_COUNT/$MAX_RETRIES)..."
              sleep 2
              RETRY_COUNT=$((RETRY_COUNT+1))
            done

            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
              echo "ERROR: $NEW failed health check. Aborting deployment."
              docker stop $NEW
              docker rm $NEW
              exit 1
            fi
            sed -i "s/server \(app_blue\|app_green\):3000;/server $NEW:3000;/" /home/ubuntu/nginx/nginx.conf


            docker exec nginx nginx -s reload

            echo "Nginx reloaded, traffic switched to $NEW on port $NEW_PORT."

            # Stop the old container
            if [ "$(docker ps -q -f name=$LIVE)" ]; then
              echo "Stopping old container $LIVE..."
              docker stop $LIVE
              docker rm $LIVE
            fi
